### PR TITLE
Fixes the startup of the mgo service

### LINKED ISSUE #6: Fix the start service

### PR DESCRIPTION
**Pull request by edumarcal**
Fix: #6

### CODE REVIEW

File: service_test.go [hunk 1]
```diff
@@ -136,6 +136,22 @@ var _ = Describe("MgoService", func() {
 		Expect(service.RunWithSession(pingSession)).To(BeNil())
 	})
 
+	It("should fail starting the service with no address", func() {
```
Comment (felipemfp) [inline service_test.go:139]: :+1:

**Review by felipemfp — APPROVED** [review]
LGTM :tada::+1:
